# Generated by Django 4.2.7 on 2023-12-05 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencia',
            name='mensaje',
            field=models.TextField(default='Escribe tu mensaje'),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='puntaje',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='El valor debe ser 1 o mayor.'), django.core.validators.MaxValueValidator(10, message='El valor debe ser 10 o menor.')]),
        ),
        migrations.AddField(
            model_name='producto',
            name='modelo',
            field=models.CharField(default=1970, max_length=4),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='Describir producto', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fecha_salida',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
