# Generated by Django 4.2.7 on 2023-12-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_experiencia_mensaje_experiencia_puntaje_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
        migrations.AddField(
            model_name='usuario',
            name='user',
            field=models.CharField(default='valor_predeterminado', max_length=20, unique=True),
        ),
    ]
