# Generated by Django 4.2.7 on 2023-12-18 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_remove_usuario_apellido_remove_usuario_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='user',
            new_name='username',
        ),
    ]
