# Generated by Django 4.2.7 on 2023-12-24 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_delete_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha_salida',
        ),
        migrations.AlterField(
            model_name='producto',
            name='modelo',
            field=models.CharField(max_length=4),
        ),
    ]
