# Generated by Django 4.2.7 on 2023-12-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_remove_producto_fecha_salida_alter_producto_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagenProducto',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
