# Generated by Django 4.2.7 on 2023-12-26 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_alter_producto_imagenproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencia',
            name='puntaje',
            field=models.IntegerField(default=1),
        ),
    ]
