# Generated by Django 4.2.7 on 2023-12-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_alter_experiencia_id_alter_producto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='Describir producto'),
        ),
    ]
