# Generated by Django 4.2.7 on 2023-12-26 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0012_experiencia_autor_producto_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencia',
            name='autor',
        ),
    ]
